#!/bin/bash
#
# Plays a power hour through Spotify
# Usage: ./powerhour [length]

powerhour () {
    echo "Starting Power Hour ($NUMTRACKS tracks)"
    echo "Playing Track #0"
    spotify play
    for ((i=1; i<=$NUMTRACKS; i++)); do
        for j in {60..1}; do
            if [ $(( $j % 10 )) -eq 0 ]; then
                echo -n "$j, "
            fi
            sleep 1
        done
        echo "0"
        echo "Playing Track #${i}"
        spotify next
    done
    echo "You made it!"
}

spotify () {
    CMD=$1
    osascript "$(dirname $0)/SpotifyControl.scpt" $CMD
}

# Default to 60 tracks
NUMTRACKS=60
if [ ! -z $1 ]; then
    NUMTRACKS=$1
fi

powerhour $NUMTRACKS
